[package]
name = "ckan-devstaller"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
inquire = "0.7.5"
owo-colors = { version = "4.2.2", features = ["supports-colors"] }
xshell = "0.2.7"
xshell-venv = "1.3.0"
